[build]
  # Directory to publish (the frontend files)
  publish = "Frontend"
  
  # Build command (not needed for static files, but good to have)
  command = "echo 'Static frontend - no build needed'"

# Redirect API calls to your backend (you'll need to update this with your actual backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

# SPA fallback - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
