# Render.com deployment configuration for VMIS Backend

# Build Configuration - Native .NET approach
buildCommand: "./render-build.sh"
publishPath: "publish"
startCommand: "dotnet VehicleBackend.dll"

# Environment
runtime: "dotnet"

# Health Check
healthCheckPath: "/api/health"

# Auto Deploy
autoDeployBranch: "main"
